### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AhlamAbdullah** [inforkgodara/whatsapp-bulk-messages-without-saving-contacts#10]
this message show up when i runn 
Traceback (most recent call last):
  File "C:\Users\ahlam\PycharmProjects\pythonProject\Data analyst\whatsup\whats.py", line 12, in <module>
    excel_data = pandas.read_excel('Recipients data.xlsx', sheet_name='Recipients')
  File "C:\Users\ahlam\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\excel\_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\ahlam\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\excel\_base.py", line 1496, in __init__
    ext = inspect_excel_format(
  File "C:\Users\ahlam\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\excel\_base.py", line 1371, in inspect_excel_format
    with get_handle(
  File "C:\Users\ahlam\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Recipients data.xlsx'

**Comment by rakhaevandy27** [comment]
its seems like u missing some file that related to [Recipients data.xlsx](https://github.com/inforkgodara/whatsapp-bulk-messages-without-saving-contacts/blob/master/Recipients%20data.xlsx)

if you want to change the file location, u can change `excel_data = pandas.read_excel('Recipients data.xlsx', sheet_name='Recipients')` @AhlamAbdullah
